packages:
  - ./

patchedDependencies:
  '@pixi/sound': patches/@pixi__sound.patch

allowBuilds:
  '@prisma/client': false
  '@tailwindcss/oxide': true
  better-sqlite3: false
  esbuild: true
  sharp: true
  supabase: true

# minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  # Renovate security update: drizzle-orm@0.45.2
  - drizzle-orm@0.45.2
